/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input {
	int num[100];
	int n;
};
typedef struct input input;

#define ADD_PROG 0x2ff0ffff
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADDPROC 1
extern  int * addproc_1(input *, CLIENT *);
extern  int * addproc_1_svc(input *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADDPROC 1
extern  int * addproc_1();
extern  int * addproc_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input (XDR *, input*);

#else /* K&R C */
extern bool_t xdr_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
