/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
addproc_1_svc(input *argp, struct svc_req *rqstp)
{
	static int  result;
	 printf("clients request accepted\n");
	 int i=0;result=0;
	 for(i=0;i<argp->n;i++){
	 	result+=argp->num[i];
	 }
	return &result;
}
